version: "3.1"

volumes:
  clickhouse_database:

services:
  sqlpad:
    image: sqlpad/sqlpad:5
    ports:
      - 3101:3000
    # hostname: "sqlpad"
    environment:
      # SQLPAD_BASE_URL: "/sqlpad"
      SQLPAD_ADMIN: "admin@sqlpad.com"
      SQLPAD_ADMIN_PASSWORD: "admin"
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__clickhouse__name: ClickHouse
      SQLPAD_CONNECTIONS__clickhouse__driver: clickhouse
      SQLPAD_CONNECTIONS__clickhouse__host: clickhouse
      SQLPAD_CONNECTIONS__clickhouse__database: tutorial
      SQLPAD_CONNECTIONS__clickhouse__username: default
      SQLPAD_CONNECTIONS__clickhouse__password:

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - clickhouse_database:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true
