name: Docker Images Multi-Platform

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read
  packages: write

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "xpert-api", context: ".deploy/api", image_name: "xpert-api-demo" }
          - { name: "xpert-webapp", context: ".deploy/webapp", image_name: "xpert-webapp-demo" }
        platform: [ "linux/amd64", "linux/arm64" ]

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/xpert-ai/${{ matrix.service.image_name }}
            metadc/${{ matrix.service.image_name }}
            registry.cn-hangzhou.aliyuncs.com/metad/${{ matrix.service.image_name }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.context }}/Dockerfile
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/xpert-ai/${{ matrix.service.image_name }}:latest
            metadc/${{ matrix.service.image_name }}:latest
            registry.cn-hangzhou.aliyuncs.com/metad/${{ matrix.service.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "xpert-api", image_name: "xpert-api-demo" }
          - { name: "xpert-webapp", image_name: "xpert-webapp-demo" }

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Platform Manifest
        uses: docker/manifest-create-action@v1
        with:
          image: |
            ghcr.io/xpert-ai/${{ matrix.service.image_name }}:latest
            metadc/${{ matrix.service.image_name }}:latest
            registry.cn-hangzhou.aliyuncs.com/metad/${{ matrix.service.image_name }}:latest
          platforms: |
            linux/amd64
            linux/arm64

      - name: Push Manifest to Docker Registries
        run: |
          docker push ghcr.io/xpert-ai/${{ matrix.service.image_name }}:latest
          docker push metadc/${{ matrix.service.image_name }}:latest
          docker push registry.cn-hangzhou.aliyuncs.com/metad/${{ matrix.service.image_name }}:latest
