name: Build and Publish Docker Images Demo

on:
  push:
    branches: [ "develop" ]

jobs:

  ocap-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: docker/build-push-action@v3
      with:
          context: .
          file: ./.deploy/api/Dockerfile
          load: true
          platforms: linux/amd64
          tags: |
              ghcr.io/meta-d/ocap-api-demo:latest
              metadc/ocap-api-demo:latest
              registry.cn-hangzhou.aliyuncs.com/metad/ocap-api-demo:latest
          cache-from: type=registry,ref=metadc/ocap-api-demo:latest
          cache-to: type=inline
    - name: Docker images list
      run: |
          sudo docker image list
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Registry
      run: |
          docker push ghcr.io/meta-d/ocap-api-demo:latest

  ocap-webapp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: docker/build-push-action@v3
      with:
          context: .
          file: ./.deploy/webapp/Dockerfile
          load: true
          platforms: linux/amd64
          tags: |
              ghcr.io/meta-d/ocap-webapp-demo:latest
              metadc/ocap-webapp-demo:latest
              registry.cn-hangzhou.aliyuncs.com/metad/ocap-webapp-demo:latest
          cache-from: type=registry,ref=metadc/ocap-webapp-demo:latest
          cache-to: type=inline
    - name: Docker images list
      run: |
          sudo docker image list
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Registry
      run: |
          docker push ghcr.io/meta-d/ocap-webapp-demo:latest