name: Publish Docker Images to Aliyun Container Registry

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  ocap-api:

    runs-on: ubuntu-latest

    steps:
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push to Docker Hub Registry
          run: |
            docker pull ghcr.io/meta-d/ocap-api-demo:latest
            docker tag ghcr.io/meta-d/ocap-api-demo:latest metadc/ocap-api-demo:latest
            docker push metadc/ocap-api-demo:latest