name: Publish Docker Images to Aliyun Container Registry

on:
  push:
    branches: [ "develop" ]
    tags:
      - '*'
  pull_request:
    branches: [ "develop" ]

jobs:

  ocap-api:

    runs-on: ubuntu-latest

    steps:
        - name: Log GitHub Tag
          env:
            GITHUB_REF_NAME: ${{ github.ref_name }}
          run: |
            echo "Current Git Tag: ${GITHUB_REF_NAME#refs/tags/}"
            echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
            echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"